### ISSUE TITLE
Feature request: CMake support

### ISSUE THREAD

**Issue by MaxKotlan** [AnvilOnline/AnvilClient#11]
Even though the project is not cross-platform, I think it would still would benefit from a CMake build system. This would make it easier to set up and link external dependencies, like [cpprestsdk](https://github.com/Microsoft/cpprestsdk.git). Also, ElDorito uses the CMake build system.

**Comment by kiwidoggie** [comment]
I don't see why this would be useful, it adds a extra/different step, also won't configure the other projects correctly without minor adjustments (which are already outlined in the Getting Started of the wiki). Maybe I'm just missing something here

**Comment by MaxKotlan** [comment]
It's useful for making sure developers have the external dependencies that are required before they attempt building the project. If a developer does not have the external dependencies installed, they may get include errors such as `cannot open source file "cef_app.h"`, because they are trying to build the project without the external dependencies installed. The developer may also receive cryptic linking errors if they include the header files but don't properly link the library. If the external dependencies required are not kept up to date in the documentation, a developer then has to search the internet to figure out what dependency they have to install. This can be a long tedious process of trial and error.

If you were to use a build system like cmake, it would warn you _before_ you built the project of any missing external dependencies. For instance, instead of getting the include error that mentions a header file isn't found, you receive an error along the lines of `Could NOT find cpprestsdk`. This makes the whole building process so much easier, because you are able to figure out what you need to install to make it work. Also in my personal opinion, it is much easier to manage your external libraries in cmake than it is using visual studio.

It does seem somewhat annoying to add every source file you create to a CMakeLists.txt file, however it definitely makes your project more organized and efficient in the long run.

**Comment by kiwidoggie** [comment]
It has been decided, we are not using CMake for a non-cross platform project. The instructions for the build dependencies are on the Wiki on how to build the project (they use env variables). Introducing CMAKE would incur more development and tweaking time for something that Visual Studio does out of the box just fine.
