### ISSUE TITLE
English fix patch fails.

### ISSUE THREAD

**Issue by twist84** [AnvilOnline/AnvilClient#8]
Zedd updated the 12.x sandtrap build english fix patches here http://pastebin.com/1tap8tGc.

Low priority.

**Comment by kiwidoggie** [comment]
Just confirming this is for ElDorito and not AnvilOnline? (Anvil doesn't use that patching system is the reason I asked)

**Comment by twist84** [comment]
No its for Anvil and I fixed it by editing the source.
https://github.com/AnvilOnline/AnvilClient/pull/9/files

**Comment by YottaBiter** [comment]
Just simply edit your 'game.cfg' with Notepad++.
Change "russian" and "ru" **to** "english" and "en".

**Comment by kiwidoggie** [comment]
Closing issue, because it was resolved via the game. Thanks @Yottabiter I was working off of some "false assumptions" and the code for English patching will be removed.
